LangString addOrReinstall ${LANG_ENGLISH} "Repair or reinstall ServerForge"
LangString alreadyInstalled ${LANG_ENGLISH} "ServerForge is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already on this PC. Choose what you want to do, then click Next."
LangString appRunning ${LANG_ENGLISH} "ServerForge is still running. Close it, then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "ServerForge is still running.$\nClick OK to close it automatically."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose a maintenance option."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ServerForge."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the current install"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep the current install (downgrades without uninstall are disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "Could not close ServerForge. Close it yourself, then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer ServerForge is already installed. Uninstall it first if you really want this older build."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ServerForge is already installed. Uninstalling first is recommended."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for this installer. Use the graphical installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall ServerForge."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ServerForge"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall the current version first"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 failed to install. ServerForge needs it to run. Restart the installer and try again."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: downloading WebView2 failed - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: WebView2 install failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed"
LangString deleteAppData ${LANG_ENGLISH} "Also delete ServerForge application data"
