use std::collections::BTreeMap;
use std::path::Path;

use crate::error::AppResult;
use crate::models::{PropertyField, ServerProperties};

const KNOWN: &[(&str, &str, &str, &[&str], Option<&str>)] = &[
    ("motd", "Message of the Day", "text", &[], Some("Shown in the multiplayer server list.")),
    ("server-port", "Server Port", "number", &[], Some("Default is 25565.")),
    ("max-players", "Max Players", "number", &[], None),
    ("difficulty", "Difficulty", "select", &["peaceful", "easy", "normal", "hard"], None),
    ("gamemode", "Gamemode", "select", &["survival", "creative", "adventure", "spectator"], None),
    ("online-mode", "Online Mode", "bool", &[], Some("Verify players with Microsoft/Mojang.")),
    ("pvp", "PVP", "bool", &[], None),
    ("allow-flight", "Allow Flight", "bool", &[], None),
    ("view-distance", "View Distance", "number", &[], None),
    ("simulation-distance", "Simulation Distance", "number", &[], None),
    ("white-list", "Whitelist", "bool", &[], None),
    ("spawn-monsters", "Spawn Monsters", "bool", &[], None),
    ("spawn-animals", "Spawn Animals", "bool", &[], None),
    ("spawn-npcs", "Spawn NPCs", "bool", &[], None),
    ("enable-command-block", "Command Blocks", "bool", &[], None),
    ("level-name", "World Name", "text", &[], None),
    ("level-seed", "World Seed", "text", &[], None),
    ("level-type", "Level Type", "text", &[], None),
    ("hardcore", "Hardcore", "bool", &[], None),
    ("max-world-size", "Max World Size", "number", &[], None),
    ("spawn-protection", "Spawn Protection", "number", &[], None),
    ("network-compression-threshold", "Compression Threshold", "number", &[], None),
];

pub fn parse_properties(raw: &str) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    for line in raw.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = trimmed.split_once('=') {
            map.insert(k.trim().to_string(), v.to_string());
        }
    }
    map
}

pub fn to_editor(raw: &str) -> ServerProperties {
    let map = parse_properties(raw);
    let mut fields: Vec<PropertyField> = KNOWN
        .iter()
        .map(|(key, label, kind, options, hint)| PropertyField {
            key: (*key).to_string(),
            label: (*label).to_string(),
            value: map.get(*key).cloned().unwrap_or_default(),
            kind: (*kind).to_string(),
            options: options.iter().map(|s| (*s).to_string()).collect(),
            hint: hint.map(|s| s.to_string()),
        })
        .collect();

    for (key, value) in &map {
        if !KNOWN.iter().any(|(k, ..)| k == key) {
            fields.push(PropertyField {
                key: key.clone(),
                label: key.clone(),
                value: value.clone(),
                kind: "text".into(),
                options: vec![],
                hint: None,
            });
        }
    }

    ServerProperties {
        fields,
        raw: raw.to_string(),
    }
}

pub fn apply_updates(raw: &str, updates: &BTreeMap<String, String>) -> String {
    let mut map = parse_properties(raw);
    for (k, v) in updates {
        map.insert(k.clone(), v.clone());
    }
    let mut out = String::from("# Minecraft server properties\n# Generated by ServerForge\n");
    for (k, v) in map {
        out.push_str(&k);
        out.push('=');
        out.push_str(&v);
        out.push('\n');
    }
    out
}

pub async fn read_properties_file(path: &Path) -> AppResult<ServerProperties> {
    let raw = if path.exists() {
        tokio::fs::read_to_string(path).await?
    } else {
        String::new()
    };
    Ok(to_editor(&raw))
}

pub async fn write_properties_file(path: &Path, updates: &BTreeMap<String, String>) -> AppResult<()> {
    let raw = if path.exists() {
        tokio::fs::read_to_string(path).await.unwrap_or_default()
    } else {
        String::new()
    };
    let next = apply_updates(&raw, updates);
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    tokio::fs::write(path, next).await?;
    Ok(())
}

pub fn get_port(raw: &str) -> u16 {
    parse_properties(raw)
        .get("server-port")
        .and_then(|v| v.parse().ok())
        .unwrap_or(25565)
}

pub fn get_max_players(raw: &str) -> u32 {
    parse_properties(raw)
        .get("max-players")
        .and_then(|v| v.parse().ok())
        .unwrap_or(20)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_properties() {
        let raw = "motd=Hello\nserver-port=25566\n";
        let mut updates = BTreeMap::new();
        updates.insert("pvp".into(), "false".into());
        let next = apply_updates(raw, &updates);
        assert!(next.contains("motd=Hello"));
        assert!(next.contains("pvp=false"));
        assert_eq!(get_port(&next), 25566);
        assert_eq!(get_max_players("max-players=42\n"), 42);
        assert_eq!(get_max_players(""), 20);
    }
}
